### ISSUE TITLE
get_content_url is no longer supported

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian-library#17]
It appears some traces of it are still left. Still getting this traceback with 83380c46.

```
Component librarian_library encountered an error during it's loading, installation skipped.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/librarian_core/dependencies.py", line 64, in _import_modules
    mod = importlib.import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/librarian_library/plugins.py", line 8, in <module>
    from .helpers import get_content_url
ImportError: cannot import name get_content_url
```

**Comment by afaikafk** [comment]
I think I had this one as well, it was a pyc plague
